import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { User, Bus, Route, RouteStop, StudentAllocation } from '../types/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
let bakedRoutes: Record<string, [number, number][]> = {};
try {
  const jsonPath = path.resolve(__dirname, 'baked-routes.json');
  if (fs.existsSync(jsonPath)) {
    bakedRoutes = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  }
} catch {
  /* fallback */
}

// Pre-hashed password for demo accounts ("MMU@Secure2026")
const DEFAULT_HASH = bcrypt.hashSync('MMU@Secure2026', 10);

export const SEED_USERS: User[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'ADMIN',
    fullName: 'Dr. Sandeep Sharma (Dean Fleet Logistics)',
    identifier: 'ADM-MMU-01',
    phone: '+91-1731-274475',
    campus: 'MULLANA_MAIN',
    department: 'Central Fleet Operations',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-driver-01',
    email: 'driver.rajesh@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'DRIVER',
    fullName: 'Rajesh Kumar Sharma',
    identifier: 'DRV-104',
    phone: '+91-9876543210',
    campus: 'MULLANA_MAIN',
    department: 'Transport Department',
    assignedBusId: 'bus-01',
    assignedRouteId: 'route-amb-01',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-driver-02',
    email: 'driver.gurpreet@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'DRIVER',
    fullName: 'Gurpreet Singh Saini',
    identifier: 'DRV-108',
    phone: '+91-9876543211',
    campus: 'MULLANA_MAIN',
    department: 'Transport Department',
    assignedBusId: 'bus-02',
    assignedRouteId: 'route-ynr-02',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-driver-03',
    email: 'driver.amit@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'DRIVER',
    fullName: 'Amit Verma',
    identifier: 'DRV-112',
    phone: '+91-9876543212',
    campus: 'MULLANA_MAIN',
    department: 'Transport Department',
    assignedBusId: 'bus-03',
    assignedRouteId: 'route-kkr-03',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-driver-04',
    email: 'driver.satish@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'DRIVER',
    fullName: 'Satish Chand Chauhan',
    identifier: 'DRV-115',
    phone: '+91-9876543213',
    campus: 'SADOPUR_AMBALA',
    department: 'Transport Department',
    assignedBusId: 'bus-04',
    assignedRouteId: 'route-chd-04',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-student-01',
    email: 'student.aarav@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'STUDENT',
    fullName: 'Aarav Gupta',
    identifier: '11221001',
    phone: '+91-9812300001',
    campus: 'MULLANA_MAIN',
    department: 'B.Tech CSE - 3rd Year',
    assignedBusId: 'bus-01',
    assignedRouteId: 'route-amb-01',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-student-02',
    email: 'student.sneha@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'STUDENT',
    fullName: 'Sneha Sharma',
    identifier: '11221002',
    phone: '+91-9812300002',
    campus: 'MULLANA_MAIN',
    department: 'MBBS - 2nd Professional (MMIMSR)',
    assignedBusId: 'bus-01',
    assignedRouteId: 'route-amb-01',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-student-03',
    email: 'student.rohan@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'STUDENT',
    fullName: 'Rohan Singh',
    identifier: '11221003',
    phone: '+91-9812300003',
    campus: 'MULLANA_MAIN',
    department: 'B.Pharma - 4th Year',
    assignedBusId: 'bus-02',
    assignedRouteId: 'route-ynr-02',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-student-04',
    email: 'student.priya@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'STUDENT',
    fullName: 'Priya Verma',
    identifier: '11221004',
    phone: '+91-9812300004',
    campus: 'MULLANA_MAIN',
    department: 'BDS - Final Year (Dental College)',
    assignedBusId: 'bus-03',
    assignedRouteId: 'route-kkr-03',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-student-05',
    email: 'student.vikram@mmumullana.org',
    passwordHash: DEFAULT_HASH,
    role: 'STUDENT',
    fullName: 'Vikram Mehta',
    identifier: '11221005',
    phone: '+91-9812300005',
    campus: 'SADOPUR_AMBALA',
    department: 'MBA - 1st Year (Sadopur)',
    assignedBusId: 'bus-04',
    assignedRouteId: 'route-chd-04',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ROUTES: Route[] = [
  {
    id: 'route-amb-01',
    routeCode: 'ROUTE-AMB-01',
    name: 'Ambala Cantt - MMU Mullana Express',
    description: 'Direct transit corridor connecting Ambala Cantt Railway Station via Mahesh Nagar and Saha Junction to MMU Mullana Campus.',
    originName: 'Ambala Cantt Junction',
    destinationName: 'MMU Mullana Campus Terminal',
    totalDistanceKm: 29.4,
    estimatedDurationMinutes: 48,
    campus: 'MULLANA_MAIN',
    morningDepartureTime: '07:15:00',
    eveningReturnTime: '16:45:00',
    colorHex: '#E21E26',
    isActive: true,
    stops: [
      {
        id: 'stop-amb-01',
        routeId: 'route-amb-01',
        name: 'Ambala Cantt Railway Station Bus Bay',
        landmark: 'Near Platform 1 Exit Gate',
        stopSequence: 1,
        latitude: 30.33268,
        longitude: 76.83756,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-amb-02',
        routeId: 'route-amb-01',
        name: 'Gandhi Ground / Subhash Park Halt',
        landmark: 'Opposite Subhash Park Gate',
        stopSequence: 2,
        latitude: 30.34125,
        longitude: 76.83312,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 8,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-03',
        routeId: 'route-amb-01',
        name: 'Mahesh Nagar Police Chowki Crossing',
        landmark: 'Near Jagadhri Road Flyover Base',
        stopSequence: 3,
        latitude: 30.32981,
        longitude: 76.85243,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 16,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-04',
        routeId: 'route-amb-01',
        name: 'Babyal Village Turn',
        landmark: 'Near Babyal Petrol Pump',
        stopSequence: 4,
        latitude: 30.31849,
        longitude: 76.88371,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 24,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-05',
        routeId: 'route-amb-01',
        name: 'Saha Industrial Junction',
        landmark: 'NH-344 Flyover Interchange',
        stopSequence: 5,
        latitude: 30.26410,
        longitude: 76.99420,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 35,
        isMajorHub: true,
      },
      {
        id: 'stop-amb-06',
        routeId: 'route-amb-01',
        name: 'Kalpi Bus Shelter',
        landmark: 'Near Kalpi Bus Stand Market',
        stopSequence: 6,
        latitude: 30.25890,
        longitude: 77.01830,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 41,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-07',
        routeId: 'route-amb-01',
        name: 'MMU Mullana Main Highway Gate',
        landmark: 'NH-344 Entrance Circle',
        stopSequence: 7,
        latitude: 30.25201,
        longitude: 77.04352,
        geofenceRadiusMeters: 800,
        scheduledArrivalOffsetMins: 46,
        isMajorHub: true,
      },
      {
        id: 'stop-amb-08',
        routeId: 'route-amb-01',
        name: 'MMEC Engineering Block Terminal',
        landmark: 'Bus Bay 1-4 Terminal',
        stopSequence: 8,
        latitude: 30.24853,
        longitude: 77.04402,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 48,
        isMajorHub: true,
      },
    ],
    waypoints: bakedRoutes['route-amb-01'] || [
      [76.83756, 30.33268],
      [76.83312, 30.34125],
      [76.85243, 30.32981],
      [76.88371, 30.31849],
      [76.93210, 30.29410],
      [76.99420, 30.26410],
      [77.01830, 30.25890],
      [77.03450, 30.25420],
      [77.04352, 30.25201],
      [77.04402, 30.24853],
    ],
  },
  {
    id: 'route-ynr-02',
    routeCode: 'ROUTE-YNR-02',
    name: 'Yamunanagar & Jagadhri Line',
    description: 'Servicing students and clinical consultants from Yamunanagar Workshop Chowk, Jagadhri Bus Stand, and Mustafabad to MMU Mullana Hospital.',
    originName: 'Yamunanagar Workshop Chowk',
    destinationName: 'MMU Mullana Hospital Terminal',
    totalDistanceKm: 34.2,
    estimatedDurationMinutes: 52,
    campus: 'MULLANA_MAIN',
    morningDepartureTime: '07:10:00',
    eveningReturnTime: '16:50:00',
    colorHex: '#3B82F6',
    isActive: true,
    stops: [
      {
        id: 'stop-ynr-01',
        routeId: 'route-ynr-02',
        name: 'Yamunanagar Workshop Chowk',
        landmark: 'Near Railway Workshop Main Gate',
        stopSequence: 1,
        latitude: 30.13420,
        longitude: 77.28890,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-02',
        routeId: 'route-ynr-02',
        name: 'Jagadhri Old Bus Stand',
        landmark: 'Civil Lines Road Halt',
        stopSequence: 2,
        latitude: 30.16540,
        longitude: 77.29810,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 10,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-03',
        routeId: 'route-ynr-02',
        name: 'Madhu Chowk Jagadhri',
        landmark: 'Near Madhu Hotel',
        stopSequence: 3,
        latitude: 30.15810,
        longitude: 77.27980,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 17,
        isMajorHub: false,
      },
      {
        id: 'stop-ynr-04',
        routeId: 'route-ynr-02',
        name: 'Aurangabad Highway Crossing',
        landmark: 'Near Aurangabad Village Arch',
        stopSequence: 4,
        latitude: 30.18340,
        longitude: 77.21560,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 28,
        isMajorHub: false,
      },
      {
        id: 'stop-ynr-05',
        routeId: 'route-ynr-02',
        name: 'Saraswati Nagar (Mustafabad) Crossing',
        landmark: 'Mustafabad Railway Crossing Junction',
        stopSequence: 5,
        latitude: 30.20890,
        longitude: 77.15120,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 38,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-06',
        routeId: 'route-ynr-02',
        name: 'Dosarka Toll Interchange',
        landmark: 'NH-344 Dosarka Flyover',
        stopSequence: 6,
        latitude: 30.23120,
        longitude: 77.08940,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 45,
        isMajorHub: false,
      },
      {
        id: 'stop-ynr-07',
        routeId: 'route-ynr-02',
        name: 'MMU Mullana Hospital Bay (Block 36)',
        landmark: 'MMIMSR Teaching Hospital Entrance',
        stopSequence: 7,
        latitude: 30.25124,
        longitude: 77.04821,
        geofenceRadiusMeters: 600,
        scheduledArrivalOffsetMins: 50,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-08',
        routeId: 'route-ynr-02',
        name: 'MMEC Engineering Campus Terminal',
        landmark: 'Bus Bay 5-8',
        stopSequence: 8,
        latitude: 30.24853,
        longitude: 77.04402,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 52,
        isMajorHub: true,
      },
    ],
    waypoints: bakedRoutes['route-ynr-02'] || [
      [77.28890, 30.13420],
      [77.29810, 30.16540],
      [77.27980, 30.15810],
      [77.21560, 30.18340],
      [77.15120, 30.20890],
      [77.08940, 30.23120],
      [77.04821, 30.25124],
      [77.04402, 30.24853],
    ],
  },
  {
    id: 'route-kkr-03',
    routeCode: 'ROUTE-KKR-03',
    name: 'Kurukshetra & Shahbad Route',
    description: 'Connecting Kurukshetra University area, Pipli GT Road Chowk, and Shahbad Markanda directly to MMU Mullana.',
    originName: 'Kurukshetra New Bus Stand',
    destinationName: 'MMU Mullana Campus Terminal',
    totalDistanceKm: 41.8,
    estimatedDurationMinutes: 58,
    campus: 'MULLANA_MAIN',
    morningDepartureTime: '07:05:00',
    eveningReturnTime: '16:45:00',
    colorHex: '#10B981',
    isActive: true,
    stops: [
      {
        id: 'stop-kkr-01',
        routeId: 'route-kkr-03',
        name: 'Kurukshetra New Bus Stand / Sector 10',
        landmark: 'Opposite Theme Park Sector 10',
        stopSequence: 1,
        latitude: 29.96980,
        longitude: 76.87840,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-kkr-02',
        routeId: 'route-kkr-03',
        name: 'Pipli GT Road Chowk',
        landmark: 'Near Pipli Bus Stand & Highway Dhaba',
        stopSequence: 2,
        latitude: 29.97920,
        longitude: 76.91450,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 12,
        isMajorHub: true,
      },
      {
        id: 'stop-kkr-03',
        routeId: 'route-kkr-03',
        name: 'Shahbad Markanda Old GT Road Chowk',
        landmark: 'Near Sugar Mill Road Crossing',
        stopSequence: 3,
        latitude: 30.16780,
        longitude: 76.87120,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 28,
        isMajorHub: true,
      },
      {
        id: 'stop-kkr-04',
        routeId: 'route-kkr-03',
        name: 'Barara Railway Station Crossing',
        landmark: 'Barara Main Bazaar Crossing',
        stopSequence: 4,
        latitude: 30.20780,
        longitude: 77.03410,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 44,
        isMajorHub: true,
      },
      {
        id: 'stop-kkr-05',
        routeId: 'route-kkr-03',
        name: 'Mullana Town Railway Crossing',
        landmark: 'Old Mullana Market Road',
        stopSequence: 5,
        latitude: 30.24120,
        longitude: 77.04010,
        geofenceRadiusMeters: 800,
        scheduledArrivalOffsetMins: 53,
        isMajorHub: false,
      },
      {
        id: 'stop-kkr-06',
        routeId: 'route-kkr-03',
        name: 'MMU Mullana Main Highway Gate',
        landmark: 'Entrance Arch',
        stopSequence: 6,
        latitude: 30.25201,
        longitude: 77.04352,
        geofenceRadiusMeters: 600,
        scheduledArrivalOffsetMins: 58,
        isMajorHub: true,
      },
    ],
    waypoints: [
      [76.87840, 29.96980],
      [76.91450, 29.97920],
      [76.87120, 30.16780],
      [77.03410, 30.20780],
      [77.04010, 30.24120],
      [77.04352, 30.25201],
      [77.04402, 30.24853],
    ],
  },
  {
    id: 'route-chd-04',
    routeCode: 'ROUTE-CHD-04',
    name: 'Chandigarh - Panchkula - Sadopur - Mullana Intercampus',
    description: 'High-speed intercampus express connecting Chandigarh Tribune Chowk, Panchkula, MMU Sadopur Campus, and MMU Mullana.',
    originName: 'Chandigarh Tribune Chowk',
    destinationName: 'MMU Mullana Campus Terminal',
    totalDistanceKm: 68.5,
    estimatedDurationMinutes: 85,
    campus: 'SADOPUR_AMBALA',
    morningDepartureTime: '06:45:00',
    eveningReturnTime: '17:00:00',
    colorHex: '#8B5CF6',
    isActive: true,
    stops: [
      {
        id: 'stop-chd-01',
        routeId: 'route-chd-04',
        name: 'Chandigarh Tribune Chowk',
        landmark: 'Near Industrial Area Phase 1 Turn',
        stopSequence: 1,
        latitude: 30.70280,
        longitude: 76.79250,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-chd-02',
        routeId: 'route-chd-04',
        name: 'Zirakpur Highway Flyover Halt',
        landmark: 'Under Zirakpur Highway Overbridge',
        stopSequence: 2,
        latitude: 30.64320,
        longitude: 76.81890,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 18,
        isMajorHub: true,
      },
      {
        id: 'stop-chd-03',
        routeId: 'route-chd-04',
        name: 'Dera Bassi Main Chowk',
        landmark: 'Near Civil Hospital Dera Bassi',
        stopSequence: 3,
        latitude: 30.58410,
        longitude: 76.84560,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 32,
        isMajorHub: false,
      },
      {
        id: 'stop-chd-04',
        routeId: 'route-chd-04',
        name: 'MMU Sadopur Campus Main Gate',
        landmark: 'Ambala-Chandigarh Highway, Sadopur',
        stopSequence: 4,
        latitude: 30.34290,
        longitude: 76.81420,
        geofenceRadiusMeters: 800,
        scheduledArrivalOffsetMins: 52,
        isMajorHub: true,
      },
      {
        id: 'stop-chd-05',
        routeId: 'route-chd-04',
        name: 'Ambala Cantt Flyover Bypass',
        landmark: 'NH-44 / NH-344 Interchange',
        stopSequence: 5,
        latitude: 30.31500,
        longitude: 76.86200,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 64,
        isMajorHub: false,
      },
      {
        id: 'stop-chd-06',
        routeId: 'route-chd-04',
        name: 'Saha Chowk Flyover Junction',
        landmark: 'Saha Industrial Area Turn',
        stopSequence: 6,
        latitude: 30.26410,
        longitude: 76.99420,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 75,
        isMajorHub: true,
      },
      {
        id: 'stop-chd-07',
        routeId: 'route-chd-04',
        name: 'MMU Mullana Main Campus Terminal',
        landmark: 'Central Garage & Student Terminal',
        stopSequence: 7,
        latitude: 30.25045,
        longitude: 77.04505,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 85,
        isMajorHub: true,
      },
    ],
    waypoints: [
      [76.79250, 30.70280],
      [76.81890, 30.64320],
      [76.84560, 30.58410],
      [76.81420, 30.34290],
      [76.86200, 30.31500],
      [76.99420, 30.26410],
      [77.04505, 30.25045],
    ],
  },
];

export const SEED_BUSES: Bus[] = [
  {
    id: 'bus-01',
    busNumber: 'BUS-01',
    registrationNumber: 'HR-54-A-1993',
    model: 'Tata Marcopolo Deluxe AC 42-Seater',
    capacity: 42,
    status: 'IDLE',
    assignedDriverId: 'usr-driver-01',
    assignedDriverName: 'Rajesh Kumar Sharma',
    assignedDriverPhone: '+91-9876543210',
    defaultRouteId: 'route-amb-01',
    defaultRouteName: 'Ambala Cantt - MMU Mullana Express',
    primaryCampus: 'MULLANA_MAIN',
    fuelLevelPercent: 88.5,
    odometerKm: 48210.5,
    isActive: true,
  },
  {
    id: 'bus-02',
    busNumber: 'BUS-02',
    registrationNumber: 'HR-54-A-2004',
    model: 'Ashok Leyland Viking 45-Seater',
    capacity: 45,
    status: 'IDLE',
    assignedDriverId: 'usr-driver-02',
    assignedDriverName: 'Gurpreet Singh Saini',
    assignedDriverPhone: '+91-9876543211',
    defaultRouteId: 'route-ynr-02',
    defaultRouteName: 'Yamunanagar & Jagadhri Line',
    primaryCampus: 'MULLANA_MAIN',
    fuelLevelPercent: 92.0,
    odometerKm: 62419.0,
    isActive: true,
  },
  {
    id: 'bus-03',
    busNumber: 'BUS-03',
    registrationNumber: 'HR-54-B-3112',
    model: 'Eicher Starline 38-Seater',
    capacity: 38,
    status: 'IDLE',
    assignedDriverId: 'usr-driver-03',
    assignedDriverName: 'Amit Verma',
    assignedDriverPhone: '+91-9876543212',
    defaultRouteId: 'route-kkr-03',
    defaultRouteName: 'Kurukshetra & Shahbad Route',
    primaryCampus: 'MULLANA_MAIN',
    fuelLevelPercent: 79.0,
    odometerKm: 34105.2,
    isActive: true,
  },
  {
    id: 'bus-04',
    busNumber: 'BUS-04',
    registrationNumber: 'HR-54-B-4089',
    model: 'BharatBenz Grande AC 44-Seater',
    capacity: 44,
    status: 'IDLE',
    assignedDriverId: 'usr-driver-04',
    assignedDriverName: 'Satish Chand Chauhan',
    assignedDriverPhone: '+91-9876543213',
    defaultRouteId: 'route-chd-04',
    defaultRouteName: 'Chandigarh - Sadopur - Mullana Intercampus',
    primaryCampus: 'SADOPUR_AMBALA',
    fuelLevelPercent: 95.0,
    odometerKm: 81240.8,
    isActive: true,
  },
  {
    id: 'bus-05',
    busNumber: 'BUS-05',
    registrationNumber: 'HR-54-C-5201',
    model: 'Tata Ultra AC 36-Seater',
    capacity: 36,
    status: 'MAINTENANCE',
    primaryCampus: 'MULLANA_MAIN',
    fuelLevelPercent: 45.0,
    odometerKm: 104520.1,
    isActive: true,
  },
];

export const SEED_ALLOCATIONS: StudentAllocation[] = [
  {
    id: 'alloc-01',
    studentId: 'usr-student-01',
    studentName: 'Aarav Gupta',
    studentRoll: '11221001',
    department: 'B.Tech CSE - 3rd Year',
    phone: '+91-9812300001',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    assignedStopId: 'stop-amb-01',
    assignedStopName: 'Ambala Cantt Railway Station Bus Bay',
    busId: 'bus-01',
    busNumber: 'BUS-01',
    academicSession: '2025-2026',
    passNumber: 'MMU-PASS-2026-0891',
    seatNumber: '12A',
    isValid: true,
    feeStatus: 'PAID',
  },
  {
    id: 'alloc-02',
    studentId: 'usr-student-02',
    studentName: 'Sneha Sharma',
    studentRoll: '11221002',
    department: 'MBBS - 2nd Professional (MMIMSR)',
    phone: '+91-9812300002',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    assignedStopId: 'stop-amb-03',
    assignedStopName: 'Mahesh Nagar Police Chowki Crossing',
    busId: 'bus-01',
    busNumber: 'BUS-01',
    academicSession: '2025-2026',
    passNumber: 'MMU-PASS-2026-0892',
    seatNumber: '14B',
    isValid: true,
    feeStatus: 'PAID',
  },
  {
    id: 'alloc-03',
    studentId: 'usr-student-03',
    studentName: 'Rohan Singh',
    studentRoll: '11221003',
    department: 'B.Pharma - 4th Year',
    phone: '+91-9812300003',
    routeId: 'route-ynr-02',
    routeName: 'Yamunanagar & Jagadhri Line',
    assignedStopId: 'stop-ynr-02',
    assignedStopName: 'Jagadhri Old Bus Stand',
    busId: 'bus-02',
    busNumber: 'BUS-02',
    academicSession: '2025-2026',
    passNumber: 'MMU-PASS-2026-1104',
    seatNumber: '08C',
    isValid: true,
    feeStatus: 'PAID',
  },
  {
    id: 'alloc-04',
    studentId: 'usr-student-04',
    studentName: 'Priya Verma',
    studentRoll: '11221004',
    department: 'BDS - Final Year (Dental College)',
    phone: '+91-9812300004',
    routeId: 'route-kkr-03',
    routeName: 'Kurukshetra & Shahbad Route',
    assignedStopId: 'stop-kkr-02',
    assignedStopName: 'Pipli GT Road Chowk',
    busId: 'bus-03',
    busNumber: 'BUS-03',
    academicSession: '2025-2026',
    passNumber: 'MMU-PASS-2026-0422',
    seatNumber: '21D',
    isValid: true,
    feeStatus: 'PAID',
  },
  {
    id: 'alloc-05',
    studentId: 'usr-student-05',
    studentName: 'Vikram Mehta',
    studentRoll: '11221005',
    department: 'MBA - 1st Year (Sadopur)',
    phone: '+91-9812300005',
    routeId: 'route-chd-04',
    routeName: 'Chandigarh - Sadopur - Mullana Intercampus',
    assignedStopId: 'stop-chd-04',
    assignedStopName: 'MMU Sadopur Campus Main Gate',
    busId: 'bus-04',
    busNumber: 'BUS-04',
    academicSession: '2025-2026',
    passNumber: 'MMU-PASS-2026-1930',
    seatNumber: '05A',
    isValid: true,
    feeStatus: 'PAID',
  },
];
