import { Route, LiveBusState, StudentAllocationResponse, FleetOverviewMetrics, TripManifestResponse, DriverProfile } from '../types/index.js';
import bakedRoutesData from './baked-routes.json';

const bakedRoutes = (bakedRoutesData as unknown) as Record<string, [number, number][]>;

export const DEFAULT_ROUTES: Route[] = [
  {
    id: 'route-amb-01',
    routeCode: 'ROUTE-AMB-01',
    name: 'Ambala Cantt - MMU Mullana Express',
    description: 'Direct transit corridor connecting Ambala Cantt Railway Station via Mahesh Nagar and Saha Junction to MMU Mullana Campus.',
    originName: 'Ambala Cantt Junction',
    destinationName: 'MMU Mullana Campus Terminal',
    totalDistanceKm: 29.4,
    estimatedDurationMinutes: 48,
    campus: 'MULLANA_MAIN',
    colorHex: '#E21E26',
    stops: [
      {
        id: 'stop-amb-01',
        routeId: 'route-amb-01',
        name: 'Ambala Cantt Railway Station Bus Bay',
        landmark: 'Near Platform 1 Exit Gate',
        stopSequence: 1,
        latitude: 30.33268,
        longitude: 76.83756,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-amb-02',
        routeId: 'route-amb-01',
        name: 'Gandhi Ground / Subhash Park Halt',
        landmark: 'Opposite Subhash Park Gate',
        stopSequence: 2,
        latitude: 30.34125,
        longitude: 76.83312,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 8,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-03',
        routeId: 'route-amb-01',
        name: 'Mahesh Nagar Police Chowki Crossing',
        landmark: 'Near Jagadhri Road Flyover Base',
        stopSequence: 3,
        latitude: 30.32981,
        longitude: 76.85243,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 16,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-04',
        routeId: 'route-amb-01',
        name: 'Babyal Village Turn',
        landmark: 'Near Babyal Petrol Pump',
        stopSequence: 4,
        latitude: 30.31849,
        longitude: 76.88371,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 24,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-05',
        routeId: 'route-amb-01',
        name: 'Saha Industrial Junction',
        landmark: 'NH-344 Flyover Interchange',
        stopSequence: 5,
        latitude: 30.26410,
        longitude: 76.99420,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 35,
        isMajorHub: true,
      },
      {
        id: 'stop-amb-06',
        routeId: 'route-amb-01',
        name: 'Kalpi Bus Shelter',
        landmark: 'Near Kalpi Bus Stand Market',
        stopSequence: 6,
        latitude: 30.25890,
        longitude: 77.01830,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 41,
        isMajorHub: false,
      },
      {
        id: 'stop-amb-07',
        routeId: 'route-amb-01',
        name: 'MMU Mullana Main Highway Gate',
        landmark: 'NH-344 Entrance Circle',
        stopSequence: 7,
        latitude: 30.25201,
        longitude: 77.04352,
        geofenceRadiusMeters: 800,
        scheduledArrivalOffsetMins: 46,
        isMajorHub: true,
      },
      {
        id: 'stop-amb-08',
        routeId: 'route-amb-01',
        name: 'MMEC Engineering Block Terminal',
        landmark: 'Bus Bay 1-4 Terminal',
        stopSequence: 8,
        latitude: 30.24853,
        longitude: 77.04402,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 48,
        isMajorHub: true,
      },
    ],
    waypoints: bakedRoutes['route-amb-01'] || [
      [76.83756, 30.33268],
      [76.83312, 30.34125],
      [76.85243, 30.32981],
      [76.88371, 30.31849],
      [76.93210, 30.29410],
      [76.99420, 30.26410],
      [77.01830, 30.25890],
      [77.03450, 30.25420],
      [77.04352, 30.25201],
      [77.04402, 30.24853],
    ],
  },
  {
    id: 'route-ynr-02',
    routeCode: 'ROUTE-YNR-02',
    name: 'Yamunanagar & Jagadhri Line',
    description: 'Servicing students and clinical consultants from Yamunanagar Workshop Chowk, Jagadhri Bus Stand, and Mustafabad to MMU Mullana Hospital.',
    originName: 'Yamunanagar Workshop Chowk',
    destinationName: 'MMU Mullana Hospital Terminal',
    totalDistanceKm: 34.2,
    estimatedDurationMinutes: 52,
    campus: 'MULLANA_MAIN',
    colorHex: '#3B82F6',
    stops: [
      {
        id: 'stop-ynr-01',
        routeId: 'route-ynr-02',
        name: 'Yamunanagar Workshop Chowk',
        landmark: 'Near Railway Workshop Main Gate',
        stopSequence: 1,
        latitude: 30.13420,
        longitude: 77.28890,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-02',
        routeId: 'route-ynr-02',
        name: 'Jagadhri Old Bus Stand',
        landmark: 'Civil Lines Road Halt',
        stopSequence: 2,
        latitude: 30.16540,
        longitude: 77.29810,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 10,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-03',
        routeId: 'route-ynr-02',
        name: 'Madhu Chowk Jagadhri',
        landmark: 'Near Madhu Hotel',
        stopSequence: 3,
        latitude: 30.15810,
        longitude: 77.27980,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 17,
        isMajorHub: false,
      },
      {
        id: 'stop-ynr-04',
        routeId: 'route-ynr-02',
        name: 'MMU Mullana Hospital Bay (Block 36)',
        landmark: 'MMIMSR Teaching Hospital Entrance',
        stopSequence: 4,
        latitude: 30.25124,
        longitude: 77.04821,
        geofenceRadiusMeters: 600,
        scheduledArrivalOffsetMins: 50,
        isMajorHub: true,
      },
      {
        id: 'stop-ynr-05',
        routeId: 'route-ynr-02',
        name: 'MMEC Engineering Campus Terminal',
        landmark: 'Bus Bay 5-8',
        stopSequence: 5,
        latitude: 30.24853,
        longitude: 77.04402,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 52,
        isMajorHub: true,
      },
    ],
    waypoints: bakedRoutes['route-ynr-02'] || [
      [77.28890, 30.13420],
      [77.29810, 30.16540],
      [77.27980, 30.15810],
      [77.04821, 30.25124],
      [77.04402, 30.24853],
    ],
  },
  {
    id: 'route-kkr-03',
    routeCode: 'ROUTE-KKR-03',
    name: 'Kurukshetra & Shahbad Route',
    description: 'Connecting Kurukshetra University area, Pipli GT Road Chowk, and Shahbad Markanda directly to MMU Mullana.',
    originName: 'Kurukshetra New Bus Stand',
    destinationName: 'MMU Mullana Campus Terminal',
    totalDistanceKm: 41.8,
    estimatedDurationMinutes: 58,
    campus: 'MULLANA_MAIN',
    colorHex: '#10B981',
    stops: [
      {
        id: 'stop-kkr-01',
        routeId: 'route-kkr-03',
        name: 'Kurukshetra New Bus Stand / Sector 10',
        landmark: 'Opposite Theme Park Sector 10',
        stopSequence: 1,
        latitude: 29.96980,
        longitude: 76.87840,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-kkr-02',
        routeId: 'route-kkr-03',
        name: 'Pipli GT Road Chowk',
        landmark: 'Near Pipli Bus Stand & Highway Dhaba',
        stopSequence: 2,
        latitude: 29.97920,
        longitude: 76.91450,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 12,
        isMajorHub: true,
      },
      {
        id: 'stop-kkr-03',
        routeId: 'route-kkr-03',
        name: 'MMEC Engineering Campus Terminal',
        landmark: 'Bus Bay 9-12',
        stopSequence: 3,
        latitude: 30.24853,
        longitude: 77.04402,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 58,
        isMajorHub: true,
      },
    ],
    waypoints: bakedRoutes['route-kkr-03'] || [
      [76.87840, 29.96980],
      [76.91450, 29.97920],
      [77.04402, 30.24853],
    ],
  },
  {
    id: 'route-chd-04',
    routeCode: 'ROUTE-CHD-04',
    name: 'Chandigarh / Zirakpur - MMU Sadopur Campus',
    description: 'Fast commuter corridor running from Chandigarh Tribune Chowk via Zirakpur to MMU Sadopur Ambala Campus.',
    originName: 'Chandigarh Tribune Chowk',
    destinationName: 'MMU Sadopur Campus Main Gate',
    totalDistanceKm: 38.6,
    estimatedDurationMinutes: 54,
    campus: 'SADOPUR_AMBALA',
    colorHex: '#8B5CF6',
    stops: [
      {
        id: 'stop-chd-01',
        routeId: 'route-chd-04',
        name: 'Chandigarh Tribune Chowk Bus Bay',
        landmark: 'Near Tribune Colony Underpass',
        stopSequence: 1,
        latitude: 30.70280,
        longitude: 76.79320,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 0,
        isMajorHub: true,
      },
      {
        id: 'stop-chd-02',
        routeId: 'route-chd-04',
        name: 'Zirakpur Flyover Crossing',
        landmark: 'Below Chandigarh-Delhi Highway Flyover',
        stopSequence: 2,
        latitude: 30.64210,
        longitude: 76.81750,
        geofenceRadiusMeters: 1000,
        scheduledArrivalOffsetMins: 14,
        isMajorHub: true,
      },
      {
        id: 'stop-chd-03',
        routeId: 'route-chd-04',
        name: 'MMU Sadopur Campus Main Gate',
        landmark: 'Sadopur Administrative Block Circle',
        stopSequence: 3,
        latitude: 30.37890,
        longitude: 76.77940,
        geofenceRadiusMeters: 500,
        scheduledArrivalOffsetMins: 54,
        isMajorHub: true,
      },
    ],
    waypoints: bakedRoutes['route-chd-04'] || [
      [76.79320, 30.70280],
      [76.81750, 30.64210],
      [76.77940, 30.37890],
    ],
  },
];

export const DEFAULT_LIVE_BUSES: LiveBusState[] = [
  {
    busId: 'bus-01',
    busNumber: 'BUS-01',
    registrationNumber: 'HR-54-A-1101',
    model: 'Tata Marcopolo Deluxe AC 42-Seater',
    status: 'IDLE',
    capacity: 42,
    boardedCount: 0,
    driverName: 'Rajesh Kumar Sharma',
    driverPhone: '+91-9876543210',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    latitude: null,
    longitude: null,
    speedKmh: 0,
    bearing: 0,
    altitudeM: null,
    accuracyM: null,
    lastPing: null,
    hasFix: false,
    upcomingStopName: 'Parked at Campus Terminal (Awaiting Run)',
    distanceToNextStopMeters: 0,
    etaMinutesUpcomingStop: 0,
  },
  {
    busId: 'bus-02',
    busNumber: 'BUS-02',
    registrationNumber: 'HR-54-A-1102',
    model: 'Tata Marcopolo Starbus 38-Seater',
    status: 'IDLE',
    capacity: 38,
    boardedCount: 0,
    driverName: 'Gurpreet Singh Saini',
    driverPhone: '+91-9876543211',
    routeId: 'route-ynr-02',
    routeName: 'Yamunanagar & Jagadhri Line',
    latitude: null,
    longitude: null,
    speedKmh: 0,
    bearing: 0,
    altitudeM: null,
    accuracyM: null,
    lastPing: null,
    hasFix: false,
    upcomingStopName: 'Parked at Workshop Depot',
    distanceToNextStopMeters: 0,
    etaMinutesUpcomingStop: 0,
  },
  {
    busId: 'bus-03',
    busNumber: 'BUS-03',
    registrationNumber: 'HR-54-A-1103',
    model: 'Ashok Leyland Sunshine 45-Seater',
    status: 'IDLE',
    capacity: 45,
    boardedCount: 0,
    driverName: 'Amit Verma',
    driverPhone: '+91-9876543212',
    routeId: 'route-kkr-03',
    routeName: 'Kurukshetra & Shahbad Route',
    latitude: null,
    longitude: null,
    speedKmh: 0,
    bearing: 0,
    altitudeM: null,
    accuracyM: null,
    lastPing: null,
    hasFix: false,
    upcomingStopName: 'Parked at Pipli Staging Area',
    distanceToNextStopMeters: 0,
    etaMinutesUpcomingStop: 0,
  },
  {
    busId: 'bus-04',
    busNumber: 'BUS-04',
    registrationNumber: 'HR-04-B-2204',
    model: 'BharatBenz Glider AC 36-Seater',
    status: 'IDLE',
    capacity: 36,
    boardedCount: 0,
    driverName: 'Satish Chand Chauhan',
    driverPhone: '+91-9876543213',
    routeId: 'route-chd-04',
    routeName: 'Chandigarh / Zirakpur - MMU Sadopur',
    latitude: null,
    longitude: null,
    speedKmh: 0,
    bearing: 0,
    altitudeM: null,
    accuracyM: null,
    lastPing: null,
    hasFix: false,
    upcomingStopName: 'Parked at Sadopur Terminal',
    distanceToNextStopMeters: 0,
    etaMinutesUpcomingStop: 0,
  },
];

export const DEFAULT_STUDENTS = [
  {
    id: 'std-1001',
    fullName: 'Aarav Gupta',
    rollNumber: '11221001',
    department: 'B.Tech Computer Science (3rd Yr)',
    phone: '+91-9812300001',
    email: 'aarav.11221001@mmumullana.org',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    stopId: 'stop-amb-01',
    stopName: 'Ambala Cantt Railway Station Bus Bay',
    passNumber: 'MMU-P-2026-001',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1002',
    fullName: 'Priya Sharma',
    rollNumber: '11221002',
    department: 'MBBS - 2nd Prof',
    phone: '+91-9812300002',
    email: 'priya.11221002@mmumullana.org',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    stopId: 'stop-amb-03',
    stopName: 'Mahesh Nagar Police Chowki Crossing',
    passNumber: 'MMU-P-2026-002',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1003',
    fullName: 'Rohan Verma',
    rollNumber: '11221003',
    department: 'B.Pharmacy - Final Yr',
    phone: '+91-9812300003',
    email: 'rohan.11221003@mmumullana.org',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    stopId: 'stop-amb-05',
    stopName: 'Saha Industrial Junction',
    passNumber: 'MMU-P-2026-003',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1004',
    fullName: 'Simran Kaur',
    rollNumber: '11221004',
    department: 'BDS - Dental Sciences',
    phone: '+91-9812300004',
    email: 'simran.11221004@mmumullana.org',
    routeId: 'route-ynr-02',
    routeName: 'Yamunanagar & Jagadhri Line',
    stopId: 'stop-ynr-01',
    stopName: 'Yamunanagar Workshop Chowk',
    passNumber: 'MMU-P-2026-004',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1005',
    fullName: 'Aditya Malik',
    rollNumber: '11221005',
    department: 'BCA - 1st Year',
    phone: '+91-9812300005',
    email: 'aditya.11221005@mmumullana.org',
    routeId: 'route-kkr-03',
    routeName: 'Kurukshetra & Shahbad Route',
    stopId: 'stop-kkr-01',
    stopName: 'Pipli Bus Stand Flyover',
    passNumber: 'MMU-P-2026-005',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1006',
    fullName: 'Ananya Saini',
    rollNumber: '11221006',
    department: 'B.Sc Nursing - 2nd Yr',
    phone: '+91-9812300006',
    email: 'ananya.11221006@mmumullana.org',
    routeId: 'route-chd-04',
    routeName: 'Chandigarh / Zirakpur - MMU Sadopur',
    stopId: 'stop-chd-01',
    stopName: 'Tribune Chowk Bus Bay',
    passNumber: 'MMU-P-2026-006',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1007',
    fullName: 'Harsh Vardhan',
    rollNumber: '11221007',
    department: 'B.Tech Mechanical Engineering',
    phone: '+91-9812300007',
    email: 'harsh.11221007@mmumullana.org',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    stopId: 'stop-amb-04',
    stopName: 'Babyal Village Turn',
    passNumber: 'MMU-P-2026-007',
    status: 'ACTIVE' as const,
  },
  {
    id: 'std-1008',
    fullName: 'Mehak Deep Kaur',
    rollNumber: '11221008',
    department: 'B.Tech IT - 3rd Year',
    phone: '+91-9812300008',
    email: 'mehak.11221008@mmumullana.org',
    routeId: 'route-ynr-02',
    routeName: 'Yamunanagar & Jagadhri Line',
    stopId: 'stop-ynr-02',
    stopName: 'Jagadhri Old Bus Stand',
    passNumber: 'MMU-P-2026-008',
    status: 'ACTIVE' as const,
  },
];

export const DEFAULT_STUDENT_ALLOCATION: StudentAllocationResponse = {
  allocation: {
    id: 'alloc-01',
    studentId: 'usr-student-01',
    routeId: 'route-amb-01',
    assignedStopId: 'stop-amb-01',
    busId: 'bus-01',
    academicSession: '2025-2026',
    passNumber: 'MMU-PASS-11221001',
    seatNumber: '14',
    feeStatus: 'PAID',
  },
  route: DEFAULT_ROUTES[0],
  stop: DEFAULT_ROUTES[0].stops[0],
  bus: {
    id: 'bus-01',
    busNumber: 'BUS-01',
    registrationNumber: 'HR-54-A-1101',
    capacity: 42,
    assignedDriverName: 'Rajesh Kumar Sharma',
    assignedDriverPhone: '+91-9876543210',
  },
  liveTracking: {
    isTripActive: false,
    currentCoordinates: null,
    hasFix: false,
    speedKmh: 0,
    bearing: 0,
    distanceToStopMeters: 0,
    etaMinutes: 0,
    isWithinGeofence: false,
    lastPing: undefined,
  },
};

export const DEFAULT_FLEET_OVERVIEW: FleetOverviewMetrics = {
  totalFleetCount: 4,
  activeTripsCount: 0,
  idleBusesCount: 4,
  maintenanceCount: 0,
  totalStudentsEnrolled: 8,
  totalStudentsBoardedToday: 0,
  activeAlertsCount: 0,
  recentAlerts: [],
};

export const DEFAULT_TRIP_MANIFEST: TripManifestResponse = {
  trip: {
    id: 'trip-demo-01',
    busId: 'bus-01',
    busNumber: 'BUS-01',
    routeId: 'route-amb-01',
    routeName: 'Ambala Cantt - MMU Mullana Express',
    status: 'IDLE',
    direction: 'CAMPUS_BOUND',
    startedAt: '',
    totalPassengersBoarded: 0,
  },
  route: DEFAULT_ROUTES[0],
  totalEnrolledStudents: 8,
  totalBoarded: 0,
  stopsManifest: DEFAULT_ROUTES[0].stops.map((stop) => ({
    stopId: stop.id,
    stopName: stop.name,
    stopSequence: stop.stopSequence,
    landmark: stop.landmark,
    latitude: stop.latitude,
    longitude: stop.longitude,
    totalEnrolled: 1,
    boardedCount: 0,
    students: [
      {
        studentId: 'usr-student-01',
        studentName: 'Aarav Gupta',
        rollNumber: '11221001',
        department: 'B.Tech CSE - 3rd Year',
        phone: '+91-9812300001',
        passNumber: 'MMU-P-2026-001',
        status: 'PENDING' as const,
      },
    ],
  })),
};

export const DEFAULT_DRIVERS: DriverProfile[] = [
  {
    id: 'drv-01',
    fullName: 'Rajesh Kumar Sharma',
    phone: '+91-9876543210',
    licenseNumber: 'HR-04-2015-0045129',
    assignedBusId: 'bus-01',
    assignedBusNumber: 'BUS-01',
    assignedRouteId: 'route-amb-01',
    assignedRouteName: 'Ambala Cantt - MMU Mullana Express',
    status: 'ACTIVE',
    experienceYears: 12,
    emergencyContact: '+91-9876543299',
  },
  {
    id: 'drv-02',
    fullName: 'Gurpreet Singh Saini',
    phone: '+91-9876543211',
    licenseNumber: 'HR-02-2018-0091823',
    assignedBusId: 'bus-02',
    assignedBusNumber: 'BUS-02',
    assignedRouteId: 'route-ynr-02',
    assignedRouteName: 'Yamunanagar & Jagadhri Line',
    status: 'ACTIVE',
    experienceYears: 9,
    emergencyContact: '+91-9876543298',
  },
  {
    id: 'drv-03',
    fullName: 'Amit Verma',
    phone: '+91-9876543212',
    licenseNumber: 'HR-07-2016-0033104',
    assignedBusId: 'bus-03',
    assignedBusNumber: 'BUS-03',
    assignedRouteId: 'route-kkr-03',
    assignedRouteName: 'Kurukshetra & Shahbad Route',
    status: 'ACTIVE',
    experienceYears: 14,
    emergencyContact: '+91-9876543297',
  },
  {
    id: 'drv-04',
    fullName: 'Satish Chand Chauhan',
    phone: '+91-9876543213',
    licenseNumber: 'CH-01-2014-0019283',
    assignedBusId: 'bus-04',
    assignedBusNumber: 'BUS-04',
    assignedRouteId: 'route-chd-04',
    assignedRouteName: 'Chandigarh / Zirakpur - MMU Sadopur',
    status: 'ACTIVE',
    experienceYears: 16,
    emergencyContact: '+91-9876543296',
  },
];
